package com.bits.canvas.common.enums;

public enum EmailType {

	HOP_EMAIL_TEMPLATE,
	CONFIRM_EMAIL_TEMPLATE,
	WELCOME_EMAIL_TEMPLATE,
	POST_EMAIL_TEMPLATE,
	UTAXI_EMAIL_TEMPLATE,
	BOOK_EMAIL_TEMPLATE,
	FORGOT_EMAIL_TEMPLATE;

}
