package com.bits.canvas.common.enums;

public enum SMSType {

	HOP_TEMPLATE,
	CONFIRM_TEMPLATE,
	VERIFY_TEMPLATE,
	REJECT_TEMPLATE,
	POST_TEMPLATE,
	CANCEL_BY_HOP_TEMPLATE,
	CANCEL_BY_POST_TEMPLATE,
	FORGOT_PWD_TEMPLATE,
	BOOK_TEMPLATE;

}
